apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-auth
  namespace: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-auth
  template:
    metadata:
      labels:
        app: service-auth
    spec:
      containers:
        - name: service-auth
          image: 005783449450.dkr.ecr.us-east-1.amazonaws.com/sinistre/auth:latest
          ports:
            - containerPort: 8091
          env:
            - name: eureka.client.service-url.defaultZone
              value: "http://discovery:8761/eureka/"
            - name: spring.datasource.url
              value: "jdbc:postgresql://postgres:5432/authentification"
            - name: spring.datasource.username
              value: "postgres"
            - name: spring.datasource.password
              value: "0000"

---
apiVersion: v1
kind: Service
metadata:
  name: service-authentification
  namespace: insurance
spec:
  selector:
    app: service-auth
  ports:
    - port: 8091
      targetPort: 8091
  type: ClusterIP