apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-sinistre
  namespace: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-sinistre
  template:
    metadata:
      labels:
        app: service-sinistre
    spec:
      containers:
      - name: service-sinistre
        image: 005783449450.dkr.ecr.us-east-1.amazonaws.com/sinistre/sinistre:latest
        ports:
        - containerPort: 8094
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/service_sinistre"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "0000"

---
apiVersion: v1
kind: Service
metadata:
  name: service-sinistre
  namespace: insurance
spec:
  selector:
    app: service-sinistre
  ports:
  - port: 8094
    targetPort: 8094
  type: ClusterIP