apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-assurance
  namespace: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-assurance
  template:
    metadata:
      labels:
        app: service-assurance
    spec:
      containers:
        - name: service-assurance
          image: 005783449450.dkr.ecr.us-east-1.amazonaws.com/sinistre/assurance:latest
          ports:
            - containerPort: 8093
          env:
            - name: eureka.client.service-url.defaultZone
              value: "http://discovery:8761/eureka/"
            - name: spring.datasource.url
              value: "jdbc:postgresql://postgres:5432/service_assurance"
            - name: spring.datasource.username
              value: "postgres"
            - name: spring.datasource.password
              value: "0000"

---
apiVersion: v1
kind: Service
metadata:
  name: service-assurance
  namespace: insurance
spec:
  selector:
    app: service-assurance
  ports:
    - port: 8093
      targetPort: 8093
  type: ClusterIP