apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: insurance
data:
  init-db.sql: |
    CREATE DATABASE authentification;
    CREATE DATABASE service_assurance;
    CREATE DATABASE service_sinistre;
    CREATE DATABASE service_admin;